language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.9-dev
    - python: 3.8
    - python: 3.7
    - python: 3.6

# whitelist
# gh-pages is otherwise ignored by Travis CI
# Use a regex to whitelist gh-pages and all branches
branches:
  only:
    - gh-pages
    - /.*/

install:
  - pip install -r requirements.txt
  - pip install black coveralls

script:
  - coverage run --append --source scripts test/test_gpo_member_photos.py
  - coverage run --append --source scripts scripts/missing.py

after_success:
  - coverage report
  - coveralls
