name: Test

on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U wheel
          python -m pip install -r requirements.txt
          python -m pip install coverage

      - name: Tox tests
        shell: bash
        run: |
          coverage run  --append --source scripts test/test_gpo_member_photos.py
          coverage run  --append --source scripts scripts/missing.py
          coverage report
          coverage xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3.1.5
        with:
          name: Python ${{ matrix.python-version }}

  success:
    needs: test
    runs-on: ubuntu-latest
    name: Test successful
    steps:
      - name: Success
        run: echo Test successful
